#!/bin/bash -e

export GTKVERSION=${GTKVERSION:-2}
export EXTRAMAKEFLAGS=${EXTRAMAKEFLAGS:-" -Wfatal-errors "}

find -maxdepth 2 -name Makefile|while read
	do
		pushd "$(dirname $REPLY)"
			make ${1}
		popd
	done